#!/usr/bin/env node
/**
 * Converts the plain-JS lesson content in content/src/ into typed TS modules under
 * src/data/generated/. Content is authored as `window.X = …;` so that many agents on
 * many machines can write it in parallel without touching app code (docs/CONTRACTS.md C8).
 *
 * Usage: node scripts/convert-content.mjs [--watch]
 */
import { readFileSync, writeFileSync, mkdirSync, existsSync, watch } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const SRC = join(ROOT, 'content', 'src');
const OUT = join(ROOT, 'src', 'data', 'generated');

/** file → { global, type } — the contract in docs/CONTRACTS.md C8. */
const FILES = [
  { file: 'data-components.js', global: 'COMPONENTS', kind: 'components' },
  { file: 'data-components-b.js', global: 'COMPONENTS_B', kind: 'components' },
  { file: 'data-components-c.js', global: 'COMPONENTS_C', kind: 'components' },
  { file: 'data-steps-a.js', global: 'STEPS_A', kind: 'steps' },
  { file: 'data-steps-b.js', global: 'STEPS_B', kind: 'steps' },
  { file: 'data-steps-b1.js', global: 'STEPS_B1', kind: 'steps' },
  { file: 'data-steps-b2.js', global: 'STEPS_B2', kind: 'steps' },
  { file: 'data-steps-c.js', global: 'STEPS_C', kind: 'steps' },
  { file: 'data-steps-c2.js', global: 'STEPS_C2', kind: 'steps' },
  { file: 'data-chaos.js', global: 'CHAOS', kind: 'chaos' },
];

import { resolveChaosEntry } from './chaos-entry-map.mjs';

const BANNER = (src) =>
  `/* GENERATED by scripts/convert-content.mjs — DO NOT EDIT.\n * source: content/src/${src}\n * Re-run \`pnpm convert\` after changing the source. */\n/* eslint-disable */\n// @ts-nocheck\n`;

function readGlobal(path, globalName) {
  const code = readFileSync(path, 'utf8');
  const sandbox = { window: {} };
  // Content files are trusted, first-party, and pure data literals.
  new Function('window', code)(sandbox.window);
  return { value: sandbox.window[globalName], code };
}

/** The 87 canonical node ids, parsed out of the frozen types file. */
function loadNodeIds() {
  const types = readFileSync(join(ROOT, 'src', 'data', 'types.ts'), 'utf8');
  const block = types.split('export const NODE_IDS = [')[1].split('] as const;')[0];
  return new Set([...block.matchAll(/'([a-z0-9]+)'/g)].map((m) => m[1]));
}

function convert() {
  mkdirSync(OUT, { recursive: true });
  const nodeIds = loadNodeIds();
  const present = [];
  const stepIds = new Set();
  const warnings = [];

  for (const entry of FILES) {
    const path = join(SRC, entry.file);
    if (!existsSync(path)) continue; // content lands incrementally — skip quietly

    let parsed;
    try {
      parsed = readGlobal(path, entry.global);
    } catch (err) {
      warnings.push(`${entry.file}: failed to evaluate — ${err.message}`);
      continue;
    }
    let value = parsed.value;
    if (value == null) {
      warnings.push(`${entry.file}: window.${entry.global} is undefined — skipped`);
      continue;
    }

    if (entry.kind === 'components') {
      // Interrupted authoring runs can leave placeholder keys; drop anything that is
      // not a real component id.
      const cleaned = {};
      let dropped = 0;
      for (const [k, v] of Object.entries(value)) {
        if (nodeIds.has(k)) cleaned[k] = v;
        else dropped++;
      }
      if (dropped) warnings.push(`${entry.file}: dropped ${dropped} non-NodeId key(s)`);
      value = cleaned;
    }

    if (entry.kind === 'steps') {
      for (const s of value) stepIds.add(s.id);
    }

    const outName = entry.file.replace(/\.js$/, '.ts');
    writeFileSync(
      join(OUT, outName),
      `${BANNER(entry.file)}const ${entry.global} = ${JSON.stringify(value, null, 1)};\nexport default ${entry.global};\n`,
      'utf8',
    );
    present.push({ ...entry, outName, count: Array.isArray(value) ? value.length : Object.keys(value).length });
  }

  // Chaos entry points are resolved last, once every step id is known.
  const chaosEntry = present.find((p) => p.kind === 'chaos');
  if (chaosEntry) {
    const path = join(SRC, chaosEntry.file);
    const chaos = readGlobal(path, chaosEntry.global).value;
    for (const [id, scenario] of Object.entries(chaos)) {
      const authored = scenario.entryAfter ?? '';
      const resolved = resolveChaosEntry(id, authored, stepIds);
      if (resolved === null) {
        warnings.push(`chaos.${id}: entryAfter '${authored}' does not resolve to any step`);
      } else if (resolved !== authored) {
        warnings.push(`chaos.${id}: entryAfter '${authored}' → '${resolved}'`);
        scenario.entryAfter = resolved;
      }
    }
    writeFileSync(
      join(OUT, chaosEntry.outName),
      `${BANNER(chaosEntry.file)}const ${chaosEntry.global} = ${JSON.stringify(chaos, null, 1)};\nexport default ${chaosEntry.global};\n`,
      'utf8',
    );
  }

  // A barrel of exactly what exists, so src/data/index.ts never imports a missing file.
  const stepFiles = present.filter((p) => p.kind === 'steps');
  const compFiles = present.filter((p) => p.kind === 'components');
  const barrel = [
    '/* GENERATED by scripts/convert-content.mjs — DO NOT EDIT. */',
    "import type { Step, ComponentMap, ChaosMap } from '../types';",
    ...present.map((p) => `import ${p.global} from './${p.outName.replace(/\.ts$/, '')}';`),
    '',
    `export const RAW_STEPS: Step[] = [${stepFiles.map((p) => `...(${p.global} as unknown as Step[])`).join(', ')}];`,
    `export const RAW_COMPONENTS = Object.assign({}, ${compFiles.map((p) => p.global).join(', ') || '{}'}) as unknown as ComponentMap;`,
    `export const RAW_CHAOS = (${chaosEntry ? chaosEntry.global : '{}'}) as unknown as ChaosMap;`,
    '',
  ].join('\n');
  writeFileSync(join(OUT, 'index.ts'), barrel, 'utf8');

  const totalSteps = present.filter((p) => p.kind === 'steps').reduce((n, p) => n + p.count, 0);
  console.log(`convert-content: ${present.length} file(s) → src/data/generated/`);
  for (const p of present) console.log(`  ${p.outName.padEnd(24)} ${String(p.count).padStart(4)} ${p.kind}`);
  console.log(`  total steps: ${totalSteps}`);
  for (const w of warnings) console.log(`  ⚠ ${w}`);
}

convert();

if (process.argv.includes('--watch')) {
  console.log('convert-content: watching content/src …');
  let timer = null;
  watch(SRC, () => {
    clearTimeout(timer);
    timer = setTimeout(() => {
      try {
        convert();
      } catch (err) {
        console.error('convert-content failed:', err.message);
      }
    }, 150);
  });
}
